import { QueryRunner } from 'typeorm';
import { Employee } from '../../modules/employees/entities/employee.entity';
import { Person } from '../../modules/persons/entities/person.entity';
import { EducationLevel } from '../../modules/persons/enums/education-level.enum';
import { GenderType } from '../../modules/persons/enums/gender-type.enum';
import { MaritalStatus } from '../../modules/persons/enums/marital-status.enum';

export async function seedEmployees(queryRunner: QueryRunner) {
  const personRepo = queryRunner.manager.getRepository(Person);
  const employeeRepo = queryRunner.manager.getRepository(Employee);

  const employeesData = [
    {
      id: 2,
      person: {
        fullName: 'سلمى علي حسين',
        motherName: 'هند علي',
        birthDate: new Date('1988-03-22'),
        birthPlace: 'رام الله',
        nationalId: '9876543211',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 38,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤولة شؤون المتطوعين',
        jobDetails: 'تنسيق ومتابعة جميع أعمال المتطوعين في الجمعية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'خدمة اجتماعية',
        mobilePhone: '0599123456',
        whatsappNumber: '0599123456',
        notes: 'تتمتع بخبرة واسعة في مجال العمل الخيري',
      },
      employee: {
        position: 'منسقة متطوعين',
        hireDate: new Date('2016-07-01'),
        terminationDate: null,
        notes: 'مسؤولة عن تسجيل وتدريب المتطوعين',
      },
    },
    {
      id: 3,
      person: {
        fullName: 'علي محمود عبد الله',
        motherName: 'سعاد محمود',
        birthDate: new Date('1992-11-10'),
        birthPlace: 'نابلس',
        nationalId: '9876543212',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 43,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤول جمع التبرعات',
        jobDetails: 'متابعة الحملات الخيرية والتبرعات المالية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة أعمال',
        mobilePhone: '0599234567',
        whatsappNumber: '0599234567',
        notes: 'لديه خبرة في تنمية الموارد والتواصل مع الجهات المانحة',
      },
      employee: {
        position: 'مسؤول جمع التبرعات',
        hireDate: new Date('2018-05-20'),
        terminationDate: null,
        notes: 'تنظيم الحملات الشهرية والخطط التمويلية',
      },
    },
    {
      id: 4,
      person: {
        fullName: 'منى سامي الحسن',
        motherName: 'ليلى سامي',
        birthDate: new Date('1991-08-05'),
        birthPlace: 'غزة',
        nationalId: '9876543213',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 37,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'أخصائية اجتماعية',
        jobDetails: 'تقديم الدعم النفسي والاجتماعي للعائلات المحتاجة',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'خدمة اجتماعية',
        mobilePhone: '0599345678',
        whatsappNumber: '0599345678',
        notes: 'تعمل بشكل مباشر مع مستفيدي الجمعية',
      },
      employee: {
        position: 'أخصائية اجتماعية',
        hireDate: new Date('2017-09-15'),
        terminationDate: null,
        notes: 'إعداد تقارير الحالة ومتابعة المشاريع الاجتماعية',
      },
    },
    {
      id: 5,
      person: {
        fullName: 'خالد يوسف سالم',
        motherName: 'مها يوسف',
        birthDate: new Date('1987-12-12'),
        birthPlace: 'بيت لحم',
        nationalId: '9876543214',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 44,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول لوجستيات',
        jobDetails: 'إدارة المستودعات والمساعدات الموزعة للمحتاجين',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.Secondary,
        universityMajor: '',
        mobilePhone: '0599456789',
        whatsappNumber: '0599456789',
        notes: 'خبرة في العمليات الميدانية والتوزيع',
      },
      employee: {
        position: 'مسؤول لوجستيات',
        hireDate: new Date('2015-03-01'),
        terminationDate: null,
        notes: 'متابعة المخزون وتوزيع المساعدات',
      },
    },
    {
      id: 6,
      person: {
        fullName: 'ياسمين رامي العبد',
        motherName: 'هالة رامي',
        birthDate: new Date('1993-04-18'),
        birthPlace: 'جنين',
        nationalId: '9876543215',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 38,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة تعليم',
        jobDetails: 'تنظيم ورش تعليمية للأطفال والشباب',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'تربية',
        mobilePhone: '0599567890',
        whatsappNumber: '0599567890',
        notes: 'تعمل في البرامج التعليمية الخاصة بالجمعية',
      },
      employee: {
        position: 'مسؤولة تعليم',
        hireDate: new Date('2019-02-10'),
        terminationDate: null,
        notes: 'إدارة الفعاليات التعليمية والورش التدريبية',
      },
    },
    {
      id: 7,
      person: {
        fullName: 'رامي عبد الله حسن',
        motherName: 'سارة عبد الله',
        birthDate: new Date('1989-07-30'),
        birthPlace: 'الخليل',
        nationalId: '9876543216',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 43,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول مشاريع',
        jobDetails: 'متابعة وتنفيذ مشاريع الجمعية المختلفة',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة أعمال',
        mobilePhone: '0599678901',
        whatsappNumber: '0599678901',
        notes: 'يتمتع بخبرة واسعة في إدارة المشاريع',
      },
      employee: {
        position: 'مسؤول مشاريع',
        hireDate: new Date('2016-06-01'),
        terminationDate: null,
        notes: 'إعداد خطط المشاريع ومتابعتها',
      },
    },
    {
      id: 8,
      person: {
        fullName: 'هدى سمير علي',
        motherName: 'منى سمير',
        birthDate: new Date('1994-10-20'),
        birthPlace: 'طولكرم',
        nationalId: '9876543217',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 37,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة إعلام',
        jobDetails: 'إدارة حملات الجمعية على مواقع التواصل الاجتماعي',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إعلام',
        mobilePhone: '0599789012',
        whatsappNumber: '0599789012',
        notes: 'تدير الحملات الإعلامية وتحرير المحتوى',
      },
      employee: {
        position: 'مسؤولة إعلام',
        hireDate: new Date('2020-09-01'),
        terminationDate: null,
        notes: 'تنسيق مع فرق الإعلام وإدارة المحتوى الرقمي',
      },
    },
    {
      id: 9,
      person: {
        fullName: 'سعيد فؤاد محمود',
        motherName: 'جميلة فؤاد',
        birthDate: new Date('1986-02-12'),
        birthPlace: 'رام الله',
        nationalId: '9876543218',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 44,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول دعم لوجستي',
        jobDetails: 'توفير المواد والمعدات للفرق الميدانية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.Secondary,
        universityMajor: '',
        mobilePhone: '0599890123',
        whatsappNumber: '0599890123',
        notes: 'مسؤول عن تجهيز الفرق الميدانية بكل ما تحتاجه',
      },
      employee: {
        position: 'مسؤول دعم لوجستي',
        hireDate: new Date('2014-05-05'),
        terminationDate: null,
        notes: 'متابعة المعدات والمواد الميدانية',
      },
    },
    {
      id: 10,
      person: {
        fullName: 'نجلاء محمود العلي',
        motherName: 'هالة محمود',
        birthDate: new Date('1991-01-25'),
        birthPlace: 'غزة',
        nationalId: '9876543219',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 39,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة تمويل المشاريع',
        jobDetails: 'تقديم الدعم المالي للمشاريع والمستفيدين',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة أعمال',
        mobilePhone: '0599901234',
        whatsappNumber: '0599901234',
        notes: 'تعمل على متابعة التمويل والموازنات الخاصة بالمشاريع',
      },
      employee: {
        position: 'مسؤولة تمويل',
        hireDate: new Date('2017-08-15'),
        terminationDate: null,
        notes: 'إعداد ميزانيات المشاريع ومتابعة الدعم المالي',
      },
    },

    {
      id: 11,
      person: {
        fullName: 'أحمد سامي الخطيب',
        motherName: 'فاطمة سامي',
        birthDate: new Date('1989-03-12'),
        birthPlace: 'جنين',
        nationalId: '9876543220',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 43,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مشرف فرق تطوعية',
        jobDetails: 'تنسيق فرق المتطوعين وتنظيم الأنشطة الميدانية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'خدمة اجتماعية',
        mobilePhone: '0599012345',
        whatsappNumber: '0599012345',
        notes: 'لديه خبرة في إدارة الفرق التطوعية',
      },
      employee: {
        position: 'مشرف فرق تطوعية',
        hireDate: new Date('2016-04-01'),
        terminationDate: null,
        notes: 'متابعة أداء الفرق وتقديم الدعم اللوجستي',
      },
    },
    {
      id: 12,
      person: {
        fullName: 'ليلى عبد الرحمن سعيد',
        motherName: 'منى عبد الرحمن',
        birthDate: new Date('1992-06-18'),
        birthPlace: 'الخليل',
        nationalId: '9876543221',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 38,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'أخصائية دعم نفسي',
        jobDetails: 'تقديم الدعم النفسي للمستفيدين من الجمعية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'علم النفس',
        mobilePhone: '0599123457',
        whatsappNumber: '0599123457',
        notes: 'متخصصة في متابعة الحالات الفردية للأطفال والشباب',
      },
      employee: {
        position: 'أخصائية دعم نفسي',
        hireDate: new Date('2018-02-15'),
        terminationDate: null,
        notes: 'متابعة جلسات الدعم الفردية والجماعية',
      },
    },
    {
      id: 13,
      person: {
        fullName: 'رامي فوزي الزعبي',
        motherName: 'هالة فوزي',
        birthDate: new Date('1987-11-22'),
        birthPlace: 'بيت لحم',
        nationalId: '9876543222',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 44,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول مشاريع تنموية',
        jobDetails: 'إدارة وتنفيذ المشاريع التنموية في المجتمع',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة مشاريع',
        mobilePhone: '0599234568',
        whatsappNumber: '0599234568',
        notes: 'لديه خبرة واسعة في المشاريع التنموية والخيرية',
      },
      employee: {
        position: 'مسؤول مشاريع تنموية',
        hireDate: new Date('2015-05-20'),
        terminationDate: null,
        notes: 'متابعة تنفيذ المشاريع والتقارير الإدارية',
      },
    },
    {
      id: 14,
      person: {
        fullName: 'نورا سامي الطيب',
        motherName: 'هند سامي',
        birthDate: new Date('1990-09-05'),
        birthPlace: 'غزة',
        nationalId: '9876543223',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 37,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤولة توعية صحية',
        jobDetails: 'إعداد حملات التوعية الصحية للمستفيدين',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'تثقيف صحي',
        mobilePhone: '0599345679',
        whatsappNumber: '0599345679',
        notes: 'خبرة في التوعية الصحية وخدمات المجتمع',
      },
      employee: {
        position: 'مسؤولة توعية صحية',
        hireDate: new Date('2017-03-15'),
        terminationDate: null,
        notes: 'تنظيم البرامج والحملات الصحية للمستفيدين',
      },
    },
    {
      id: 15,
      person: {
        fullName: 'عمار مصطفى عبد الله',
        motherName: 'ليلى مصطفى',
        birthDate: new Date('1988-12-12'),
        birthPlace: 'نابلس',
        nationalId: '9876543224',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 43,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول تبرعات عينية',
        jobDetails: 'جمع وتوزيع المواد الغذائية والمساعدات العينية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.Secondary,
        universityMajor: '',
        mobilePhone: '0599456780',
        whatsappNumber: '0599456780',
        notes: 'خبرة في تنظيم التوزيعات الميدانية',
      },
      employee: {
        position: 'مسؤول تبرعات عينية',
        hireDate: new Date('2014-08-10'),
        terminationDate: null,
        notes: 'متابعة استلام وتوزيع المساعدات العينية',
      },
    },
    {
      id: 16,
      person: {
        fullName: 'سارة يوسف الحداد',
        motherName: 'مها يوسف',
        birthDate: new Date('1993-05-23'),
        birthPlace: 'طولكرم',
        nationalId: '9876543225',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 38,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة تدريب',
        jobDetails: 'تقديم التدريب للمتطوعين والموظفين',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'تربية',
        mobilePhone: '0599567891',
        whatsappNumber: '0599567891',
        notes: 'تنظم برامج التدريب الدورية للموظفين والمتطوعين',
      },
      employee: {
        position: 'مسؤولة تدريب',
        hireDate: new Date('2018-01-15'),
        terminationDate: null,
        notes: 'إعداد المناهج التدريبية وتنفيذها',
      },
    },
    {
      id: 17,
      person: {
        fullName: 'خالد سامي العطار',
        motherName: 'هالة سامي',
        birthDate: new Date('1986-09-10'),
        birthPlace: 'الخليل',
        nationalId: '9876543226',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 44,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول تمويل المشاريع',
        jobDetails: 'متابعة الميزانيات وتوفير الموارد المالية للمشاريع',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة أعمال',
        mobilePhone: '0599678902',
        whatsappNumber: '0599678902',
        notes: 'لديه خبرة في التمويل وإدارة الموازنات',
      },
      employee: {
        position: 'مسؤول تمويل',
        hireDate: new Date('2015-06-01'),
        terminationDate: null,
        notes: 'متابعة الموارد المالية للمشاريع الخيرية',
      },
    },
    {
      id: 18,
      person: {
        fullName: 'نورا عبد الله سعيد',
        motherName: 'سارة عبد الله',
        birthDate: new Date('1991-11-20'),
        birthPlace: 'غزة',
        nationalId: '9876543227',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 37,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة إعلامية',
        jobDetails: 'كتابة محتوى إعلامي وإدارة مواقع الجمعية على الإنترنت',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إعلام',
        mobilePhone: '0599789013',
        whatsappNumber: '0599789013',
        notes: 'متخصصة في التسويق الرقمي وإدارة المحتوى',
      },
      employee: {
        position: 'مسؤولة إعلامية',
        hireDate: new Date('2019-09-01'),
        terminationDate: null,
        notes: 'متابعة الحملات الإعلامية وتنفيذ استراتيجيات التواصل',
      },
    },
    {
      id: 19,
      person: {
        fullName: 'حسام تحسين',
        motherName: 'جميلة فؤاد',
        birthDate: new Date('1986-02-12'),
        birthPlace: 'رام الله',
        nationalId: '9876543228',
        nationality: 'فلسطيني',
        motherNationality: 'فلسطينية',
        gender: GenderType.MALE,
        shoeSize: 44,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مسؤول دعم لوجستي',
        jobDetails: 'توفير المواد والمعدات للفرق الميدانية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.Secondary,
        universityMajor: '',
        mobilePhone: '0599890124',
        whatsappNumber: '0599890124',
        notes: 'مسؤول عن تجهيز الفرق الميدانية بكل ما تحتاجه',
      },
      employee: {
        position: 'مسؤول دعم لوجستي',
        hireDate: new Date('2014-05-05'),
        terminationDate: null,
        notes: 'متابعة المعدات والمواد الميدانية',
      },
    },
    {
      id: 20,
      person: {
        fullName: 'نجلاء محمود عبد الرحمن',
        motherName: 'هالة محمود',
        birthDate: new Date('1991-01-25'),
        birthPlace: 'غزة',
        nationalId: '9876543229',
        nationality: 'فلسطينية',
        motherNationality: 'فلسطينية',
        gender: GenderType.FEMALE,
        shoeSize: 39,
        maritalStatus: MaritalStatus.Single,
        isWorking: true,
        currentJob: 'مسؤولة تمويل المشاريع',
        jobDetails: 'تقديم الدعم المالي للمشاريع والمستفيدين',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'إدارة أعمال',
        mobilePhone: '0599901235',
        whatsappNumber: '0599901235',
        notes: 'تعمل على متابعة التمويل والموازنات الخاصة بالمشاريع',
      },
      employee: {
        position: 'مسؤولة تمويل',
        hireDate: new Date('2017-08-15'),
        terminationDate: null,
        notes: 'إعداد ميزانيات المشاريع ومتابعة الدعم المالي',
      },
    },
    {
      id: 21,
      person: {
        fullName: 'محمد أحمد العلي',
        motherName: 'فاطمة محمد',
        birthDate: new Date('1990-05-15'),
        birthPlace: 'دمشق',
        nationalId: '9876543210',
        nationality: 'سوري',
        motherNationality: 'سورية',
        gender: GenderType.MALE,
        shoeSize: 42,
        maritalStatus: MaritalStatus.Married,
        isWorking: true,
        currentJob: 'مطور برمجيات',
        jobDetails: 'متخصص في تطوير تطبيقات الويب للمنظمات غير الربحية',
        isSmoker: false,
        healthStatus: 'جيد',
        isHealthInsuranceUsed: true,
        educationLevel: EducationLevel.University,
        universityMajor: 'هندسة البرمجيات',
        mobilePhone: '0998765432',
        whatsappNumber: '0998765432',
        notes: 'موظف متميز في قسم التطوير التقني للجمعية',
      },
      employee: {
        position: 'مطور برمجيات أول',
        hireDate: new Date('2020-01-15'),
        terminationDate: null,
        notes: 'مسؤول عن تطوير وصيانة التطبيقات الداخلية والخدمات الإلكترونية',
      },
    },
  ];

  for (const employeeData of employeesData) {
    // التحقق من وجود الشخص بالرقم الوطني
    const existingPerson = await personRepo.findOne({
      where: { nationalId: employeeData.person.nationalId },
    });

    if (existingPerson) {
      console.log(
        `❌ Person with national ID ${employeeData.person.nationalId} already exists`,
      );
      continue;
    }

    // إنشاء الشخص
    const savedPerson = await personRepo.save(
      personRepo.create(employeeData.person),
    );

    // إنشاء الموظف
    await employeeRepo.save(
      employeeRepo.create({
        ...employeeData.employee,
        personId: savedPerson.id,
      }),
    );

    console.log(
      `✅ Employee ${employeeData.person.fullName} created successfully`,
    );
  }

  console.log('🎉 Employees seeding completed successfully!');
}
