import { QueryRunner } from 'typeorm';
import { FamilyRelationType } from '../../modules/family-members/enums/family-relation-type.enum';
import { CreateVisitDto } from '../../modules/visits/dtos';
import { Visit } from '../../modules/visits/entities/visit.entity';
import {
  HouseCondition,
  HouseOwnership,
  WashingMachineType,
} from '../../modules/visits/enums';
import { AlBarakaCharityIncomeAmount } from '../../modules/visits/enums/al-baraka-charity-income-amount.enum';
import { DisabilityStatus } from '../../modules/visits/enums/disability-status.enum';
import { MobileStatus } from '../../modules/visits/enums/mobile-status.enum';
import { VisitCommitteeEvaluationEnum } from '../../modules/visits/enums/visit-committee-evaluation.enum';
import { WorkingIndividualAge } from '../../modules/visits/enums/working-individual-age-status';

export async function seedVisits(queryRunner: QueryRunner) {
  const visitRepo = queryRunner.manager.getRepository(Visit);

  await visitRepo.save(visitRepo.create(visits));

  console.log('🎉 Visits seeding completed successfully!');
}

const visits: CreateVisitDto[] = [
  {
    familyId: 1,
    visitDate: new Date('2025-01-15'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'العائلة بحاجة إلى دعم غذائي إضافي، مع إمكانية توفير برامج دعم تعليمي للأطفال.',
    paperSentDateOfTheVisit: new Date('2025-01-20'),
    guardianRelationship: FamilyRelationType.FATHER,
    numberOfFamilyMembers: 6,
    numberOfRemainingFamilyMembersInTheHouse: 5,
    road: { isPaved: true, notes: 'الطريق معبدة وسهلة الوصول' },
    houseCondition: HouseCondition.ArabicEuropean,
    notes: 'المنزل نظيف لكن يعاني من رطوبة في الجدران.',
    houseOwnership: HouseOwnership.Rent,
    furnishings: { sofaSets: 1, sofas: 2, mattresses: 3, notes: 'بحالة جيدة' },
    carpetsAndMats: { carpetsCount: 3, matsCount: 2, notes: 'مستعملة قليلاً' },
    blankets: { blanketsCount: 4, notes: 'بحاجة إلى المزيد في الشتاء' },
    quilts: { quiltsCount: 2, notes: 'قديمة نوعًا ما' },
    beds: { bedsCount: 3, notes: 'سرير الأطفال مكسور' },
    wardrobes: { wardrobesCount: 2, notes: 'واحد بحالة ممتازة' },
    householdItems: {
      tables: 1,
      chairs: 4,
      televisions: 1,
      computers: 1,
      mobilePhones: MobileStatus.Available,
      notes: 'جهاز الكمبيوتر قديم وبطيء',
    },
    washingMachine: {
      count: 1,
      type: WashingMachineType.Automatic,
      notes: 'جيدة',
    },
    gasOven: { count: 1, type: 'two-burner', notes: 'مستهلكة' },
    coolingDevices: { airConditionersCount: 1, fansCount: 2 },
    refrigerator: { count: 1, notes: 'يعمل بشكل جيد' },
    heatingDevices: { dieselHeatersCount: 1, notes: 'تحتاج إلى صيانة' },
    wasteBasket: 'متوفر',
    schoolExpenses: 350000,
    clothesCondition: 'ملابس جيدة ولكن قليلة للأطفال',
    shoesCondition: 'معظمها قديم',
    foodSuppliesCondition: 'محدودة ولا تكفي أسبوع كامل',
    needsOrLuxuriesNotReportedInThePaper: 'حاجة ماسة إلى ثلاجة إضافية',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.LBP_150000,
    income: {
      amount: 200000,
      // type: 'daily_wage', // 'type' is not a valid property in IncomeDto
    },
    availableSpendingWithoutAssociation: 1200000,
    totalIncomeWithoutAssociation: 2000000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 800000,
    workingIndividual: {
      age: WorkingIndividualAge.MORE_THAN_TWO_OVER_15,
      notes: 'الأب يعمل في البناء',
    },
    disabilityOrIllness: { status: DisabilityStatus.NONE, notes: '' },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_90,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_90,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_50,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_50,
    },
    committeeMembers: ['أ. محمد', 'د. سارة'],
  },

  {
    familyId: 1,
    visitDate: new Date('2025-02-10'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'تمت ملاحظة تحسن في أوضاع النظافة، لكن الحاجة لا تزال قائمة للأثاث.',
    paperSentDateOfTheVisit: new Date('2025-02-15'),
    guardianRelationship: FamilyRelationType.MOTHER,
    numberOfFamilyMembers: 4,
    numberOfRemainingFamilyMembersInTheHouse: 4,
    road: { isPaved: false, isDirt: true, notes: 'طريق غير معبد، وصول متوسط' },
    houseCondition: HouseCondition.Floor,
    notes: 'البيت متهالك وغير مناسب للأطفال.',
    houseOwnership: HouseOwnership.Guest,
    furnishings: { sofaSets: 0, sofas: 1, mattresses: 2 },
    carpetsAndMats: { carpetsCount: 1, matsCount: 0 },
    blankets: { blanketsCount: 2 },
    quilts: { quiltsCount: 1 },
    beds: { bedsCount: 2 },
    wardrobes: { wardrobesCount: 1 },
    householdItems: {
      tables: 0,
      chairs: 2,
      televisions: 0,
      mobilePhones: MobileStatus.Available,
    },
    washingMachine: { count: 0 },
    gasOven: { count: 1, type: 'manual', notes: 'مستهلكة' },
    coolingDevices: { fansCount: 1 },
    refrigerator: { count: 0 },
    heatingDevices: { woodHeatersCount: 1 },
    wasteBasket: 'غير متوفر',
    schoolExpenses: 150000,
    clothesCondition: 'ضعيفة جدًا',
    shoesCondition: 'غير كافية',
    foodSuppliesCondition: 'شحيحة',
    needsOrLuxuriesNotReportedInThePaper: 'حاجة لفرش كامل',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.NONE,
    income: { amount: 500000, source: 'مساعدات' },
    availableSpendingWithoutAssociation: 300000,
    totalIncomeWithoutAssociation: 700000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 0,
    workingIndividual: {
      age: WorkingIndividualAge.ONE_OVER_15,
      notes: 'ابن العائلة يعمل جزئيًا',
    },
    disabilityOrIllness: {
      status: DisabilityStatus.MORE_THAN_ONE,
      notes: 'الأم مريضة بالسكر',
    },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_30,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_90,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_30,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_30,
    },
    committeeMembers: ['م. خالد', 'أ. منى'],
  },
  {
    familyId: 1,
    visitDate: new Date('2025-03-05'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'العائلة بحاجة لمتابعة شهرية لضمان الاستقرار.',
    paperSentDateOfTheVisit: new Date('2025-03-08'),
    guardianRelationship: FamilyRelationType.FATHER,
    numberOfFamilyMembers: 7,
    numberOfRemainingFamilyMembersInTheHouse: 7,
    road: {
      isPaved: false,
      isDirt: true,
      isExtreme: true,
      notes: 'طريق صعب الوصول',
    },
    houseCondition: HouseCondition.BuildingBasement,
    notes: 'الرطوبة مرتفعة جدًا.',
    houseOwnership: HouseOwnership.Rent,
    furnishings: { sofaSets: 1, sofas: 1, mattresses: 5 },
    carpetsAndMats: { carpetsCount: 2, matsCount: 3 },
    blankets: { blanketsCount: 5 },
    quilts: { quiltsCount: 3 },
    beds: { bedsCount: 4 },
    wardrobes: { wardrobesCount: 2 },
    householdItems: {
      televisions: 1,
      computers: 0,
      mobilePhones: MobileStatus.Available,
    },
    washingMachine: { count: 1, type: WashingMachineType.TwinTub },
    gasOven: { count: 1 },
    coolingDevices: { fansCount: 2 },
    refrigerator: { count: 1 },
    heatingDevices: { gasHeatersCount: 1 },
    wasteBasket: 'متوفر',
    schoolExpenses: 400000,
    clothesCondition: 'جيدة',
    shoesCondition: 'معتدلة',
    foodSuppliesCondition: 'متوسطة',
    needsOrLuxuriesNotReportedInThePaper: 'مطلوب حاسوب محمول للطلاب',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.LBP_225000,
    income: { amount: 700000, source: 'عمل مؤقت' },
    availableSpendingWithoutAssociation: 1000000,
    totalIncomeWithoutAssociation: 1700000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 900000,
    workingIndividual: {
      age: WorkingIndividualAge.MORE_THAN_TWO_OVER_15,
      notes: 'الأب والأم يعملان',
    },
    disabilityOrIllness: { status: DisabilityStatus.NONE },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_50,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_90,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_50,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_50,
    },
    committeeMembers: ['د. أحمد', 'أ. ليلى'],
  },
  {
    familyId: 2,
    visitDate: new Date('2025-01-22'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'العائلة بحاجة إلى دعم صحي عاجل بسبب مرض أحد الأبناء.',
    paperSentDateOfTheVisit: new Date('2025-01-28'),
    guardianRelationship: FamilyRelationType.MOTHER,
    numberOfFamilyMembers: 5,
    numberOfRemainingFamilyMembersInTheHouse: 5,
    road: { isPaved: true, isClose: true, notes: 'طريق ممتاز' },
    houseCondition: HouseCondition.GroundFloor,
    notes: 'المنزل جيد نسبيًا.',
    houseOwnership: HouseOwnership.Owner,
    furnishings: { sofaSets: 2, mattresses: 2 },
    carpetsAndMats: { carpetsCount: 4 },
    blankets: { blanketsCount: 6 },
    quilts: { quiltsCount: 2 },
    beds: { bedsCount: 3 },
    wardrobes: { wardrobesCount: 2 },
    householdItems: {
      televisions: 2,
      laptops: 1,
      mobilePhones: MobileStatus.Available,
    },
    washingMachine: { count: 1, type: WashingMachineType.Automatic },
    gasOven: { count: 1 },
    coolingDevices: { airConditionersCount: 2 },
    refrigerator: { count: 1 },
    heatingDevices: { electricHeatersCount: 2 },
    wasteBasket: 'متوفر',
    schoolExpenses: 250000,
    clothesCondition: 'مقبولة',
    shoesCondition: 'جيدة',
    foodSuppliesCondition: 'كافية لأسبوع',
    needsOrLuxuriesNotReportedInThePaper: 'حاجة لدواء دائم',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.LBP_150000,
    income: { amount: 2000000, source: 'راتب حكومي' },
    availableSpendingWithoutAssociation: 1800000,
    totalIncomeWithoutAssociation: 3800000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 0,
    workingIndividual: {
      age: WorkingIndividualAge.MORE_THAN_TWO_OVER_15,
      notes: 'الأب موظف حكومي',
    },
    disabilityOrIllness: {
      status: DisabilityStatus.MORE_THAN_ONE,
      notes: 'أحد الأبناء مصاب بمرض مزمن',
    },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_90,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_90,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_30,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_70,
    },
    committeeMembers: ['أ. ريم', 'م. سامر'],
  },
  {
    familyId: 2,
    visitDate: new Date('2025-02-18'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'الأسرة بحاجة لمساعدة غذائية إضافية.',
    paperSentDateOfTheVisit: new Date('2025-02-22'),
    guardianRelationship: FamilyRelationType.FATHER,
    numberOfFamilyMembers: 3,
    numberOfRemainingFamilyMembersInTheHouse: 3,
    road: { isPaved: true, notes: 'طريق جيد' },
    houseCondition: HouseCondition.Arabic,
    notes: 'بيت واسع لكن بحاجة لصيانة.',
    houseOwnership: HouseOwnership.WithFamily,
    furnishings: { sofaSets: 1, sofas: 2 },
    carpetsAndMats: { carpetsCount: 3 },
    blankets: { blanketsCount: 3 },
    quilts: { quiltsCount: 1 },
    beds: { bedsCount: 2 },
    wardrobes: { wardrobesCount: 1 },
    householdItems: { televisions: 1, microwaves: 1 },
    washingMachine: { count: 1, type: WashingMachineType.TwinTub },
    gasOven: { count: 1 },
    coolingDevices: { fansCount: 2 },
    refrigerator: { count: 1 },
    heatingDevices: { gasHeatersCount: 1 },
    wasteBasket: 'متوفر',
    schoolExpenses: 180000,
    clothesCondition: 'ضعيفة',
    shoesCondition: 'مقبولة',
    foodSuppliesCondition: 'غير كافية',
    needsOrLuxuriesNotReportedInThePaper: 'حاجة لوقود التدفئة',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.NONE,
    income: { amount: 900000, source: 'عمل حر' },
    availableSpendingWithoutAssociation: 700000,
    totalIncomeWithoutAssociation: 1600000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 0,
    workingIndividual: {
      age: WorkingIndividualAge.ONE_OVER_15,
      notes: 'الابن يعمل في ورشة',
    },
    disabilityOrIllness: { status: DisabilityStatus.NONE },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_70,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_70,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_70,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_50,
    },
    committeeMembers: ['د. منير', 'أ. هدى'],
  },
  {
    familyId: 3,
    visitDate: new Date('2025-03-12'),
    committeeNotesAndSuggestionsOfTheVisitCommittee:
      'الأسرة تعاني من ضيق شديد في المساحة وارتفاع تكاليف المعيشة.',
    paperSentDateOfTheVisit: new Date('2025-03-16'),
    guardianRelationship: FamilyRelationType.FATHER,
    numberOfFamilyMembers: 8,
    numberOfRemainingFamilyMembersInTheHouse: 8,
    road: { isPaved: false, isDirt: true, notes: 'طريق ضعيف' },
    houseCondition: HouseCondition.Shared,
    notes: 'بيت مشترك مع عائلة أخرى.',
    houseOwnership: HouseOwnership.Rent,
    furnishings: { sofas: 2, mattresses: 6 },
    carpetsAndMats: { carpetsCount: 5 },
    blankets: { blanketsCount: 6 },
    quilts: { quiltsCount: 4 },
    beds: { bedsCount: 5 },
    wardrobes: { wardrobesCount: 2 },
    householdItems: {
      televisions: 1,
      laptops: 0,
      mobilePhones: MobileStatus.Available,
    },
    washingMachine: { count: 1, type: WashingMachineType.Standard },
    gasOven: { count: 1 },
    coolingDevices: { fansCount: 1 },
    refrigerator: { count: 1 },
    heatingDevices: { woodHeatersCount: 1 },
    wasteBasket: 'غير متوفر',
    schoolExpenses: 500000,
    clothesCondition: 'ضعيفة جدًا',
    shoesCondition: 'قديمة',
    foodSuppliesCondition: 'ناقصة',
    needsOrLuxuriesNotReportedInThePaper: 'حاجة لأسرة إضافية',
    barakaAssociationIncome: AlBarakaCharityIncomeAmount.LBP_75000,
    income: { amount: 600000, source: 'عمل يومي' },
    availableSpendingWithoutAssociation: 400000,
    totalIncomeWithoutAssociation: 1000000,
    amountOfRentIfTheApplicantIsTheOnePayingIt: 700000,
    workingIndividual: {
      age: WorkingIndividualAge.MORE_THAN_TWO_OVER_15,
      notes: 'الأب يعمل يوميًا',
    },
    disabilityOrIllness: {
      status: DisabilityStatus.ONE,
      notes: 'طفل يعاني من الربو',
    },
    visitCommitteeEvaluation: {
      cleanlinessAndOrder: VisitCommitteeEvaluationEnum.PERCENT_30,
      generalMorals: VisitCommitteeEvaluationEnum.PERCENT_50,
      physicalAndMentalHealth: VisitCommitteeEvaluationEnum.PERCENT_30,
      surroundingEnvironment: VisitCommitteeEvaluationEnum.PERCENT_30,
    },
    committeeMembers: ['أ. ندى', 'م. رائد'],
  },
];
