import { QueryRunner } from 'typeorm';
import { FamilyMember } from '../../modules/family-members/entities/family-members.entity';
import { FamilyRelationType } from '../../modules/family-members/enums/family-relation-type.enum';
import { IsPresent } from '../../modules/family-members/enums/is-present.enum';
import { IsSponsored } from '../../modules/family-members/enums/is-sponsored.enum';
import { Person } from '../../modules/persons/entities/person.entity';
import { CurrentStudyStatus } from '../../modules/persons/enums/current-study-status.enum';
import { EducationLevel } from '../../modules/persons/enums/education-level.enum';
import { GenderType } from '../../modules/persons/enums/gender-type.enum';
import { MaritalStatus } from '../../modules/persons/enums/marital-status.enum';
import { SchoolType } from '../../modules/persons/enums/school-type.enum';
import { SuccessCertificateSubmission } from '../../modules/persons/enums/success-certificate-submission.enum';

export async function seedFamilyMembers(queryRunner: QueryRunner) {
  const familyMemberRepo = queryRunner.manager.getRepository(FamilyMember);
  const personRepo = queryRunner.manager.getRepository(Person);

  for (const { person, familyMember } of familyMembersData) {
    let existingPerson = await personRepo.findOne({
      where: { nationalId: person.nationalId },
    });

    if (!existingPerson) {
      existingPerson = await personRepo.save({ ...person });
      console.log(`✅ Person ${person.id} created successfully`);
    } else {
      console.log(
        `❌ Person with nationalId ${person.nationalId} already exists`,
      );
    }

    // التحقق من وجود العضو مسبقًا
    const existingFamilyMember = await familyMemberRepo.findOne({
      where: {
        familyId: familyMember.familyId,
        personId: existingPerson.id,
      },
    });

    if (!existingFamilyMember) {
      familyMember.personId = existingPerson.id; // ربط العضو بالشخص
      await familyMemberRepo.save({ ...familyMember });
      console.log(
        `✅ Family member ${familyMember.id} for family ${familyMember.familyId} created successfully`,
      );
    } else {
      console.log(
        `❌ Family member with familyId ${familyMember.familyId} and personId ${existingPerson.id} already exists`,
      );
    }
  }

  console.log('🎉 Family members seeding completed successfully!');
}

const familyMembersData = [
  {
    person: {
      id: 22,
      fullName: 'أحمد خالد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('1980-05-12'),
      birthPlace: 'دمشق',
      nationalId: '12321000001',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 42,
      maritalStatus: MaritalStatus.Married,
      isWorking: true,
      currentJob: 'مهندس كهرباء',
      jobDetails: 'يعمل في شركة الكهرباء الوطنية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'هندسة كهربائية',
      currentStudyStatus: CurrentStudyStatus.University,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة دمشق',
      mobilePhone: '09987650001',
      whatsappNumber: '09987650001',
      notes: 'وصي العائلة',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    familyMember: {
      id: 22,
      familyId: 1,
      personId: 22,
      relationType: FamilyRelationType.FATHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      isGuardian: true,
      notes: 'وصي العائلة',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
  },
  {
    person: {
      id: 23,
      fullName: 'ليلى محمود العلي',
      motherName: 'سميرة أحمد محمود',
      birthDate: new Date('1982-08-20'),
      birthPlace: 'حلب',
      nationalId: '12321000002',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 38,
      maritalStatus: MaritalStatus.Married,
      isWorking: true,
      currentJob: 'مدرسة',
      jobDetails: 'تدرس في مدرسة ابتدائية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'تربية',
      currentStudyStatus: CurrentStudyStatus.University,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة حلب',
      mobilePhone: '09987650002',
      whatsappNumber: '09987650002',
      notes: 'زوجة الأب',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
    },
    familyMember: {
      id: 23,
      familyId: 1,
      personId: 23,
      relationType: FamilyRelationType.MOTHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 2,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'زوجة الأب',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
    },
  },
  {
    person: {
      id: 24,
      fullName: 'محمد أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2005-03-10'),
      birthPlace: 'دمشق',
      nationalId: '12321000003',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 40,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'طالب في المرحلة الثانوية، يهتم بالرياضيات والعلوم',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Secondary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.Tenth_Science,
      schoolType: SchoolType.Public,
      schoolName: 'ثانوية دمشق',
      mobilePhone: '09987650003',
      whatsappNumber: '09987650003',
      notes: 'ابن الأب',
      createdAt: new Date('2024-03-05'),
      updatedAt: new Date('2024-03-05'),
    },
    familyMember: {
      id: 24,
      familyId: 1,
      personId: 24,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 3,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'ابن الأب',
      createdAt: new Date('2024-03-05'),
      updatedAt: new Date('2024-03-05'),
    },
  },
  {
    person: {
      id: 25,
      fullName: 'سارة أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2008-07-12'),
      birthPlace: 'دمشق',
      nationalId: '12321000004',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 37,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طباخة',
      jobDetails: 'تعمل طباخة في مطعم محلي وتساعد في إعداد الوجبات',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Secondary,
      universityMajor: 'هندسة غذائية',
      currentStudyStatus: CurrentStudyStatus.Eighth,
      schoolType: SchoolType.Public,
      schoolName: 'متوسطة دمشق',
      mobilePhone: '09987650004',
      whatsappNumber: '09987650004',
      notes: 'ابنة الأب',
      createdAt: new Date('2024-04-15'),
      updatedAt: new Date('2024-04-15'),
    },
    familyMember: {
      id: 25,
      familyId: 1,
      personId: 25,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 4,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'ابنة الأب',
      createdAt: new Date('2024-04-15'),
      updatedAt: new Date('2024-04-15'),
    },
  },
  {
    person: {
      id: 26,
      fullName: 'علي خالد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2010-11-05'),
      birthPlace: 'دمشق',
      nationalId: '12321000005',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 38,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Preparatory,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.Fifth,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650005',
      whatsappNumber: '09987650005',
      notes: 'ابن الأب',
      createdAt: new Date('2024-05-01'),
      updatedAt: new Date('2024-05-01'),
    },
    familyMember: {
      id: 26,
      familyId: 1,
      personId: 26,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 5,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'ابن الأب',
      createdAt: new Date('2024-05-01'),
      updatedAt: new Date('2024-05-01'),
    },
  },
  {
    person: {
      id: 27,
      fullName: 'منى أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2012-09-15'),
      birthPlace: 'دمشق',
      nationalId: '12321000006',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 36,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'مطور برمجيات',
      jobDetails:
        'أعمل في شركة تقنية متخصصة في تطوير تطبيقات الويب والهاتف المحمول، مع التركيز على تقنيات React وNode.js',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Preparatory,
      universityMajor: 'هندسة البرمجيات',
      currentStudyStatus: CurrentStudyStatus.Third,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650006',
      whatsappNumber: '09987650006',
      notes: 'ابنة الأب',
      createdAt: new Date('2024-06-10'),
      updatedAt: new Date('2024-06-10'),
    },
    familyMember: {
      id: 27,
      familyId: 1,
      personId: 27,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 6,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'ابنة الأب',
      createdAt: new Date('2024-06-10'),
      updatedAt: new Date('2024-06-10'),
    },
  },
  {
    person: {
      id: 28,
      fullName: 'خالد أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2014-01-20'),
      birthPlace: 'دمشق',
      nationalId: '12321000007',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 35,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'مدرسة',
      jobDetails: 'تدرس في مدرسة ابتدائية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: 'تربية',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650007',
      whatsappNumber: '09987650007',
      notes: 'ابن الأب',
      createdAt: new Date('2024-07-05'),
      updatedAt: new Date('2024-07-05'),
    },
    familyMember: {
      id: 28,
      familyId: 1,
      personId: 28,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 7,
      isPresent: IsPresent.PRESENT,
      isGuardian: false,
      notes: 'ابن الأب',
      createdAt: new Date('2024-07-05'),
      updatedAt: new Date('2024-07-05'),
    },
  },
  {
    person: {
      id: 29,
      fullName: 'ياسمين أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2015-06-12'),
      birthPlace: 'دمشق',
      nationalId: '12321000008',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 34,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650008',
      whatsappNumber: '09987650008',
      notes: 'ابنة الأب',
      createdAt: new Date('2024-08-01'),
      updatedAt: new Date('2024-08-01'),
    },
    familyMember: {
      id: 29,
      familyId: 1,
      personId: 29,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 8,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2024-08-01'),
      updatedAt: new Date('2024-08-01'),
    },
  },
  {
    person: {
      id: 30,
      fullName: 'رامي أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2016-09-23'),
      birthPlace: 'دمشق',
      nationalId: '12321000009',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 33,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650009',
      whatsappNumber: '09987650009',
      notes: 'ابن الأب',
      createdAt: new Date('2024-09-10'),
      updatedAt: new Date('2024-09-10'),
    },
    familyMember: {
      id: 30,
      familyId: 1,
      personId: 30,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 9,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب',
      isGuardian: false,
      createdAt: new Date('2024-09-10'),
      updatedAt: new Date('2024-09-10'),
    },
  },
  {
    person: {
      id: 31,
      fullName: 'ليان أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2017-03-18'),
      birthPlace: 'دمشق',
      nationalId: '12321000010',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 32,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650010',
      whatsappNumber: '09987650010',
      notes: 'ابنة الأب',
      createdAt: new Date('2024-10-05'),
      updatedAt: new Date('2024-10-05'),
    },
    familyMember: {
      id: 31,
      familyId: 1,
      personId: 31,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 10,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2024-10-05'),
      updatedAt: new Date('2024-10-05'),
    },
  },
  {
    person: {
      id: 32,
      fullName: 'زيد أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2018-07-30'),
      birthPlace: 'دمشق',
      nationalId: '12321000011',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 31,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650011',
      whatsappNumber: '09987650011',
      notes: 'ابن الأب',
      createdAt: new Date('2024-11-12'),
      updatedAt: new Date('2024-11-12'),
    },
    familyMember: {
      id: 32,
      familyId: 1,
      personId: 32,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 11,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب',
      isGuardian: false,
      createdAt: new Date('2024-11-12'),
      updatedAt: new Date('2024-11-12'),
    },
  },
  {
    person: {
      id: 33,
      fullName: 'نور أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2019-05-21'),
      birthPlace: 'دمشق',
      nationalId: '12321000012',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 30,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650012',
      whatsappNumber: '09987650012',
      notes: 'ابنة الأب',
      createdAt: new Date('2024-12-01'),
      updatedAt: new Date('2024-12-01'),
    },
    familyMember: {
      id: 33,
      familyId: 1,
      personId: 33,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 12,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2024-12-01'),
      updatedAt: new Date('2024-12-01'),
    },
  },
  {
    person: {
      id: 34,
      fullName: 'يوسف أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2020-02-14'),
      birthPlace: 'دمشق',
      nationalId: '12321000013',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 29,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650013',
      whatsappNumber: '09987650013',
      notes: 'ابن الأب',
      createdAt: new Date('2025-01-10'),
      updatedAt: new Date('2025-01-10'),
    },
    familyMember: {
      id: 34,
      familyId: 1,
      personId: 34,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 13,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب',
      isGuardian: false,
      createdAt: new Date('2025-01-10'),
      updatedAt: new Date('2025-01-10'),
    },
  },
  {
    person: {
      id: 35,
      fullName: 'هنا أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2021-08-18'),
      birthPlace: 'دمشق',
      nationalId: '12321000014',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 28,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650014',
      whatsappNumber: '09987650014',
      notes: 'ابنة الأب',
      createdAt: new Date('2025-02-15'),
      updatedAt: new Date('2025-02-15'),
    },
    familyMember: {
      id: 35,
      familyId: 1,
      personId: 35,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 14,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2025-02-15'),
      updatedAt: new Date('2025-02-15'),
    },
  },
  {
    person: {
      id: 36,
      fullName: 'آدم أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2022-05-21'),
      birthPlace: 'دمشق',
      nationalId: '12321000015',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 27,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650015',
      whatsappNumber: '09987650015',
      notes: 'ابن الأب',
      createdAt: new Date('2025-03-10'),
      updatedAt: new Date('2025-03-10'),
    },
    familyMember: {
      id: 36,
      familyId: 1,
      personId: 36,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 15,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب',
      isGuardian: false,
      createdAt: new Date('2025-03-10'),
      updatedAt: new Date('2025-03-10'),
    },
  },
  {
    person: {
      id: 37,
      fullName: 'جنى أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2023-01-30'),
      birthPlace: 'دمشق',
      nationalId: '12321000016',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 26,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650016',
      whatsappNumber: '09987650016',
      notes: 'ابنة الأب',
      createdAt: new Date('2025-04-05'),
      updatedAt: new Date('2025-04-05'),
    },
    familyMember: {
      id: 37,
      familyId: 1,
      personId: 37,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 16,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2025-04-05'),
      updatedAt: new Date('2025-04-05'),
    },
  },
  {
    person: {
      id: 38,
      fullName: 'راما أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2023-08-15'),
      birthPlace: 'دمشق',
      nationalId: '12321000017',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 25,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650017',
      whatsappNumber: '09987650017',
      notes: 'ابنة الأب',
      createdAt: new Date('2025-05-01'),
      updatedAt: new Date('2025-05-01'),
    },
    familyMember: {
      id: 38,
      familyId: 1,
      personId: 38,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 17,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2025-05-01'),
      updatedAt: new Date('2025-05-01'),
    },
  },
  {
    person: {
      id: 39,
      fullName: 'نوران أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2024-02-10'),
      birthPlace: 'دمشق',
      nationalId: '12321000018',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 24,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650018',
      whatsappNumber: '09987650018',
      notes: 'ابنة الأب',
      createdAt: new Date('2025-06-05'),
      updatedAt: new Date('2025-06-05'),
    },
    familyMember: {
      id: 39,
      familyId: 1,
      personId: 39,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 18,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب',
      isGuardian: false,
      createdAt: new Date('2025-06-05'),
      updatedAt: new Date('2025-06-05'),
    },
  },
  {
    person: {
      id: 40,
      fullName: 'يزن أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2024-08-12'),
      birthPlace: 'دمشق',
      nationalId: '12321000019',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.MALE,
      shoeSize: 23,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: '',
      jobDetails: '',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: '',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650019',
      whatsappNumber: '09987650019',
      notes: 'ابن الأب',
      createdAt: new Date('2025-07-01'),
      updatedAt: new Date('2025-07-01'),
    },
    familyMember: {
      id: 40,
      familyId: 1,
      personId: 40,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 19,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب',
      isGuardian: false,
      createdAt: new Date('2025-07-01'),
      updatedAt: new Date('2025-07-01'),
    },
  },
  {
    person: {
      id: 41,
      fullName: 'تالا أحمد العلي',
      motherName: 'ليلى محمود العلي',
      birthDate: new Date('2025-01-15'),
      birthPlace: 'دمشق',
      nationalId: '12321000020',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطيني',
      gender: GenderType.FEMALE,
      shoeSize: 22,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'لا يعمل',
      jobDetails: 'لا يوجد تفاصيل عمل',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.NotEnrolled,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الابتدائية',
      mobilePhone: '09987650020',
      whatsappNumber: '09987650020',
      notes: 'ابنة الأب، أصغر طفل بالعائلة',
      createdAt: new Date('2025-07-20'),
      updatedAt: new Date('2025-07-20'),
    },
    familyMember: {
      id: 41,
      familyId: 1,
      personId: 41,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 20,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب، أصغر طفل بالعائلة',
      isGuardian: false,
      createdAt: new Date('2025-07-20'),
      updatedAt: new Date('2025-07-20'),
    },
  },
  {
    person: {
      id: 42,
      fullName: 'سارة يوسف الخطيب',
      motherName: 'مريم خالد الخطيب',
      birthDate: new Date('1998-03-10'),
      birthPlace: 'حلب',
      nationalId: '12321000021',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 37,
      maritalStatus: MaritalStatus.Single,
      isWorking: true,
      currentJob: 'معلمة',
      jobDetails: 'تدرس في مدرسة ابتدائية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'تربية',
      currentStudyStatus: CurrentStudyStatus.CompletedAllStages,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الحسين الثانوية',
      mobilePhone: '09987650021',
      whatsappNumber: '09987650021',
      notes: 'ابنة الأب، طالبة متفوقة',
      createdAt: new Date('2024-08-01'),
      updatedAt: new Date('2024-08-01'),
    },
    familyMember: {
      id: 42,
      familyId: 2,
      personId: 42,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب، طالبة متفوقة',
      isGuardian: false,
      createdAt: new Date('2024-08-01'),
      updatedAt: new Date('2024-08-01'),
    },
  },
  {
    person: {
      id: 43,
      fullName: 'أحمد سامر الخطيب',
      motherName: 'مريم خالد الخطيب',
      birthDate: new Date('1995-07-21'),
      birthPlace: 'دمشق',
      nationalId: '12321000022',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 42,
      maritalStatus: MaritalStatus.Married,
      isWorking: true,
      currentJob: 'مهندس مدني',
      jobDetails: 'يعمل في مشروع بناء',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'هندسة مدنية',
      currentStudyStatus: CurrentStudyStatus.CompletedAllStages,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة دمشق',
      mobilePhone: '09987650022',
      whatsappNumber: '09987650022',
      notes: 'ابن الأب الأكبر، متزوج ولديه طفل',
      createdAt: new Date('2024-07-15'),
      updatedAt: new Date('2024-07-15'),
    },
    familyMember: {
      id: 43,
      familyId: 2,
      personId: 43,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 2,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب الأكبر، متزوج ولديه طفل',
      isGuardian: false,
      createdAt: new Date('2024-07-15'),
      updatedAt: new Date('2024-07-15'),
    },
  },
  {
    person: {
      id: 44,
      fullName: 'خالد محمود الخطيب',
      motherName: 'مريم خالد الخطيب',
      birthDate: new Date('1970-11-05'),
      birthPlace: 'اللاذقية',
      nationalId: '12321000023',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 44,
      maritalStatus: MaritalStatus.Married,
      isWorking: true,
      currentJob: 'طبيب',
      jobDetails: 'يعمل في مستشفى خاص',
      isSmoker: false,
      healthStatus: 'صحي ممتاز',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'طب',
      currentStudyStatus: CurrentStudyStatus.CompletedAllStages,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة حلب',
      mobilePhone: '09987650023',
      whatsappNumber: '09987650023',
      notes: 'الأب الوصي للعائلة',
      createdAt: new Date('2024-06-10'),
      updatedAt: new Date('2024-06-10'),
    },
    familyMember: {
      id: 44,
      familyId: 2,
      personId: 44,
      relationType: FamilyRelationType.FATHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 3,
      isPresent: IsPresent.PRESENT,
      notes: 'الأب الوصي للعائلة',
      isGuardian: true,
      createdAt: new Date('2024-06-10'),
      updatedAt: new Date('2024-06-10'),
    },
  },
  {
    person: {
      id: 45,
      fullName: 'ليلى خالد الخطيب',
      motherName: 'سلمى إبراهيم',
      birthDate: new Date('1972-02-12'),
      birthPlace: 'حماة',
      nationalId: '12321000024',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 38,
      maritalStatus: MaritalStatus.Married,
      isWorking: false,
      currentJob: 'ربة منزل',
      jobDetails: 'تدير شؤون المنزل والأطفال',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Secondary,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.NotEnrolled,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة حماة الثانوية',
      mobilePhone: '09987650024',
      whatsappNumber: '09987650024',
      notes: 'الأم الوصية، تدير شؤون المنزل',
      createdAt: new Date('2024-05-18'),
      updatedAt: new Date('2024-05-18'),
    },
    familyMember: {
      id: 45,
      familyId: 2,
      personId: 45,
      relationType: FamilyRelationType.MOTHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 4,
      isPresent: IsPresent.PRESENT,
      notes: 'الأم الوصية، تدير شؤون المنزل',
      isGuardian: false,
      createdAt: new Date('2024-05-18'),
      updatedAt: new Date('2024-05-18'),
    },
  },
  {
    person: {
      id: 46,
      fullName: 'ياسمين سامر الخطيب',
      motherName: 'ليلى خالد الخطيب',
      birthDate: new Date('2000-09-30'),
      birthPlace: 'دمشق',
      nationalId: '12321000025',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 36,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالبة',
      jobDetails: 'تدرس في جامعة دمشق',
      isSmoker: false,
      healthStatus: 'صحي ممتاز',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'علوم حاسوب',
      currentStudyStatus: CurrentStudyStatus.University,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة دمشق',
      mobilePhone: '09987650025',
      whatsappNumber: '09987650025',
      notes: 'ابنة الأب، طالبة جامعية متفوقة',
      createdAt: new Date('2024-04-22'),
      updatedAt: new Date('2024-04-22'),
    },
    familyMember: {
      id: 46,
      familyId: 2,
      personId: 46,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 5,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب، طالبة جامعية متفوقة',
      isGuardian: false,
      createdAt: new Date('2024-04-22'),
      updatedAt: new Date('2024-04-22'),
    },
  },

  {
    person: {
      id: 47,
      fullName: 'مروان حسام الخطيب',
      motherName: 'جميلة أحمد',
      birthDate: new Date('1990-01-15'),
      birthPlace: 'حلب',
      nationalId: '12321000026',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 43,
      maritalStatus: MaritalStatus.Married,
      isWorking: true,
      currentJob: 'مهندس كهرباء',
      jobDetails: 'يعمل في شركة مقاولات',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.University,
      universityMajor: 'هندسة كهربائية',
      currentStudyStatus: CurrentStudyStatus.CompletedAllStages,
      schoolType: SchoolType.Public,
      schoolName: 'جامعة حلب',
      mobilePhone: '09987650026',
      whatsappNumber: '09987650026',
      notes: 'الأب الوصي للعائلة',
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-03-10'),
    },
    familyMember: {
      id: 47,
      familyId: 3,
      personId: 47,
      relationType: FamilyRelationType.FATHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      notes: 'الأب الوصي للعائلة',
      isGuardian: true,
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-03-10'),
    },
  },
  {
    person: {
      id: 48,
      fullName: 'هند مروان الخطيب',
      motherName: 'جميلة أحمد',
      birthDate: new Date('1992-05-20'),
      birthPlace: 'دمشق',
      nationalId: '12321000027',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 37,
      maritalStatus: MaritalStatus.Married,
      isWorking: false,
      currentJob: 'ربة منزل',
      jobDetails: 'تدير شؤون المنزل',
      isSmoker: false,
      healthStatus: 'صحي ممتاز',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Secondary,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.NotEnrolled,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة دمشق الثانوية',
      mobilePhone: '09987650027',
      whatsappNumber: '09987650027',
      notes: 'الأم الوصية',
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-03-15'),
    },
    familyMember: {
      id: 48,
      familyId: 3,
      personId: 48,
      relationType: FamilyRelationType.MOTHER,
      isSponsored: IsSponsored.YES,
      memberNumber: 2,
      isPresent: IsPresent.PRESENT,
      notes: 'الأم الوصية',
      isGuardian: false,
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-03-15'),
    },
  },
  {
    person: {
      id: 49,
      fullName: 'سعيد مروان الخطيب',
      motherName: 'هند مروان الخطيب',
      birthDate: new Date('2010-09-12'),
      birthPlace: 'حلب',
      nationalId: '12321000028',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 35,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يدرس في المدرسة الابتدائية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Fifth,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الصديق الابتدائية',
      mobilePhone: '09987650028',
      whatsappNumber: '09987650028',
      notes: 'ابن الأب والأم',
      createdAt: new Date('2024-03-20'),
      updatedAt: new Date('2024-03-20'),
    },
    familyMember: {
      id: 49,
      familyId: 3,
      personId: 49,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 3,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-03-20'),
      updatedAt: new Date('2024-03-20'),
    },
  },
  {
    person: {
      id: 50,
      fullName: 'ليلى مروان الخطيب',
      motherName: 'هند مروان الخطيب',
      birthDate: new Date('2012-12-05'),
      birthPlace: 'دمشق',
      nationalId: '12321000029',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 34,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالبة',
      jobDetails: 'تدرس في المدرسة الابتدائية',
      isSmoker: false,
      healthStatus: 'صحي ممتاز',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Third,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الفارابي الابتدائية',
      mobilePhone: '09987650029',
      whatsappNumber: '09987650029',
      notes: 'ابنة الأب والأم',
      createdAt: new Date('2024-03-25'),
      updatedAt: new Date('2024-03-25'),
    },
    familyMember: {
      id: 50,
      familyId: 3,
      personId: 50,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 4,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-03-25'),
      updatedAt: new Date('2024-03-25'),
    },
  },
  {
    person: {
      id: 51,
      fullName: 'عمر مروان الخطيب',
      motherName: 'هند مروان الخطيب',
      birthDate: new Date('2015-06-18'),
      birthPlace: 'حلب',
      nationalId: '12321000030',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 33,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يدرس في الروضة',
      isSmoker: false,
      healthStatus: 'صحي ممتاز',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Primary,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.First,
      schoolType: SchoolType.Public,
      schoolName: 'روضة الحلو',
      mobilePhone: '09987650030',
      whatsappNumber: '09987650030',
      notes: 'ابن الأب والأم',
      createdAt: new Date('2024-03-28'),
      updatedAt: new Date('2024-03-28'),
    },
    familyMember: {
      id: 51,
      familyId: 3,
      personId: 51,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 5,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-03-28'),
      updatedAt: new Date('2024-03-28'),
    },
  },
  {
    person: {
      id: 52,
      fullName: 'منى مروان الخطيب',
      motherName: 'هند مروان الخطيب',
      birthDate: new Date('2008-08-14'),
      birthPlace: 'دمشق',
      nationalId: '12321000031',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.FEMALE,
      shoeSize: 36,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالبة',
      jobDetails: 'تدرس في المدرسة الإعدادية',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted:
        SuccessCertificateSubmission.Submitted_Passed,
      educationLevel: EducationLevel.Preparatory,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Seventh,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة المأمون الإعدادية',
      mobilePhone: '09987650031',
      whatsappNumber: '09987650031',
      notes: 'ابنة الأب والأم',
      createdAt: new Date('2024-03-30'),
      updatedAt: new Date('2024-03-30'),
    },
    familyMember: {
      id: 52,
      familyId: 3,
      personId: 52,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 6,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-03-30'),
      updatedAt: new Date('2024-03-30'),
    },
  },
  {
    person: {
      id: 53,
      fullName: 'يوسف مروان الخطيب',
      motherName: 'هند مروان الخطيب',
      birthDate: new Date('2018-11-02'),
      birthPlace: 'حلب',
      nationalId: '12321000032',
      nationality: 'سوري',
      motherNationality: 'سوري',
      gender: GenderType.MALE,
      shoeSize: 32,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طفل',
      jobDetails: 'لا يدرس بعد',
      isSmoker: false,
      healthStatus: 'صحي جيد',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.NotEnrolled,
      schoolType: SchoolType.Public,
      schoolName: 'روضة الزهراء',
      mobilePhone: '09987650032',
      whatsappNumber: '09987650032',
      notes: 'ابن الأب والأم',
      createdAt: new Date('2024-04-02'),
      updatedAt: new Date('2024-04-02'),
    },
    familyMember: {
      id: 53,
      familyId: 3,
      personId: 53,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 7,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-04-02'),
      updatedAt: new Date('2024-04-02'),
    },
  },

  {
    person: {
      id: 54,
      fullName: 'سالم يوسف',
      motherName: 'فاطمة حسن',
      birthDate: new Date('2013-05-14'),
      birthPlace: 'غزة',
      nationalId: '12321123454',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطينية',
      gender: GenderType.MALE,
      shoeSize: 36,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يذهب للمدرسة صباحاً',
      isSmoker: false,
      healthStatus: 'سليم',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Second,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الشهداء',
      mobilePhone: '09987650033',
      whatsappNumber: '09987650033',
      notes: 'طفل ذكي ونشيط',
      createdAt: new Date('2023-09-12'),
      updatedAt: new Date('2023-09-12'),
    },
    familyMember: {
      id: 54,
      familyId: 4,
      personId: 54,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: false,
      createdAt: new Date('2023-09-12'),
      updatedAt: new Date('2023-09-12'),
    },
  },
  {
    person: {
      id: 55,
      fullName: 'ليلى أحمد',
      motherName: 'سارة محمد',
      birthDate: new Date('2010-11-22'),
      birthPlace: 'خان يونس',
      nationalId: '12321123455',
      nationality: 'فلسطينية',
      motherNationality: 'فلسطينية',
      gender: GenderType.FEMALE,
      shoeSize: 34,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالبة',
      jobDetails: 'تدرس بالمدرسة',
      isSmoker: false,
      healthStatus: 'سليمة',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Fifth,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الفتح',
      mobilePhone: '09987650034',
      whatsappNumber: '09987650034',
      notes: 'طفلة مجتهدة',
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-01-05'),
    },
    familyMember: {
      id: 55,
      familyId: 4,
      personId: 55,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 2,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب والأم',
      isGuardian: false,
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-01-05'),
    },
  },
  {
    person: {
      id: 56,
      fullName: 'محمد علي',
      motherName: 'منى خالد',
      birthDate: new Date('2008-03-18'),
      birthPlace: 'رفح',
      nationalId: '12321123456',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطينية',
      gender: GenderType.MALE,
      shoeSize: 38,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يدرس بالمدرسة',
      isSmoker: false,
      healthStatus: 'سليم',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Seventh,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الوحدة',
      mobilePhone: '09987650035',
      whatsappNumber: '09987650035',
      notes: 'طفل نشيط ومجتهد',
      createdAt: new Date('2023-07-20'),
      updatedAt: new Date('2023-07-20'),
    },
    familyMember: {
      id: 56,
      familyId: 4,
      personId: 56,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 3,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: true,
      createdAt: new Date('2023-07-20'),
      updatedAt: new Date('2023-07-20'),
    },
  },
  {
    person: {
      id: 57,
      fullName: 'علي حسن',
      motherName: 'جميلة سعيد',
      birthDate: new Date('2012-08-05'),
      birthPlace: 'خانيونس',
      nationalId: '12321123457',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطينية',
      gender: GenderType.MALE,
      shoeSize: 37,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يدرس في الصف السادس',
      isSmoker: false,
      healthStatus: 'سليم',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Sixth,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة القدس',
      mobilePhone: '09987650036',
      whatsappNumber: '09987650036',
      notes: 'طفل هادئ ومجتهد',
      createdAt: new Date('2023-10-11'),
      updatedAt: new Date('2023-10-11'),
    },
    familyMember: {
      id: 57,
      familyId: 5,
      personId: 57,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: true,
      createdAt: new Date('2023-10-11'),
      updatedAt: new Date('2023-10-11'),
    },
  },
  {
    person: {
      id: 58,
      fullName: 'مريم خالد',
      motherName: 'هدى صالح',
      birthDate: new Date('2011-09-19'),
      birthPlace: 'غزة',
      nationalId: '12321123458',
      nationality: 'فلسطينية',
      motherNationality: 'فلسطينية',
      gender: GenderType.FEMALE,
      shoeSize: 35,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالبة',
      jobDetails: 'تدرس بالصف الخامس',
      isSmoker: false,
      healthStatus: 'سليمة',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Fifth,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة الشهداء',
      mobilePhone: '09987650037',
      whatsappNumber: '09987650037',
      notes: 'طفلة ذكية',
      createdAt: new Date('2023-12-02'),
      updatedAt: new Date('2023-12-02'),
    },
    familyMember: {
      id: 58,
      familyId: 5,
      personId: 58,
      relationType: FamilyRelationType.DAUGHTER,
      isSponsored: IsSponsored.YES,
      memberNumber: 2,
      isPresent: IsPresent.PRESENT,
      notes: 'ابنة الأب والأم',
      isGuardian: false,
      createdAt: new Date('2023-12-02'),
      updatedAt: new Date('2023-12-02'),
    },
  },
  {
    person: {
      id: 59,
      fullName: 'حسن مصطفى',
      motherName: 'عائشة فؤاد',
      birthDate: new Date('2009-06-30'),
      birthPlace: 'رفح',
      nationalId: '12321123459',
      nationality: 'فلسطيني',
      motherNationality: 'فلسطينية',
      gender: GenderType.MALE,
      shoeSize: 38,
      maritalStatus: MaritalStatus.Single,
      isWorking: false,
      currentJob: 'طالب',
      jobDetails: 'يدرس في الصف السابع',
      isSmoker: false,
      healthStatus: 'سليم',
      isHealthInsuranceUsed: true,
      isSuccessCertificateSubmitted: SuccessCertificateSubmission.No,
      educationLevel: EducationLevel.NotEnrolled,
      universityMajor: 'لا يوجد',
      currentStudyStatus: CurrentStudyStatus.Seventh,
      schoolType: SchoolType.Public,
      schoolName: 'مدرسة السلام',
      mobilePhone: '09987650038',
      whatsappNumber: '09987650038',
      notes: 'طفل مجتهد وهادئ',
      createdAt: new Date('2024-02-18'),
      updatedAt: new Date('2024-02-18'),
    },
    familyMember: {
      id: 59,
      familyId: 6,
      personId: 59,
      relationType: FamilyRelationType.SON,
      isSponsored: IsSponsored.YES,
      memberNumber: 1,
      isPresent: IsPresent.PRESENT,
      notes: 'ابن الأب والأم',
      isGuardian: true,
      createdAt: new Date('2024-02-18'),
      updatedAt: new Date('2024-02-18'),
    },
  },
];
