export enum FamilyRelationType {
  DAUGHTER = 'daughter',
  SON = 'son',
  PATER_AUNT_COUSIN = 'pater_aunt_cousin',
  PATER_UNCLE_COUSIN = 'pater_uncle_cousin',
  MATER_UNCLE_COUSIN = 'mater_uncle_cousin',
  MATER_AUNT_COUSIN = 'mater_aunt_cousin',
  MOTHER = 'mother',
  FATHER = 'father',
  GRANDMOTHER = 'grandmother',
  PATER_UNCLE = 'pater_uncle',
  MATER_UNCLE = 'mater_uncle',
  PATER_AUNT = 'pater_aunt',
  MATER_AUNT = 'mater_aunt',
  OTHER = 'other',
}
