export enum FamilyRelationType {
  DAUGHTER = 'daughter',
  SON = 'son',
  MOTHER = 'mother',
  FATHER = 'father',
  GRANDMOTHER = 'grandmother',
  GRANDFATHER = 'grandfather',
  PATERNAL_UNCLE = 'paternal_uncle',
  PATERNAL_AUNT = 'paternal_aunt',
  MATERNAL_UNCLE = 'maternal_uncle',
  MATERNAL_AUNT = 'maternal_aunt',
  PATERNAL_UNCLE_COUSIN = 'paternal_uncle_cousin',
  PATERNAL_AUNT_COUSIN = 'paternal_aunt_cousin',
  MATERNAL_UNCLE_COUSIN = 'maternal_uncle_cousin',
  MATERNAL_AUNT_COUSIN = 'maternal_aunt_cousin',
  OTHER = 'other',
}
