// Generated by i18n-validator

interface DropdownsErrorsCategorynotfoundParams {
  id: string | number
}

interface DropdownsErrorsCategorynameexistsParams {
  name: string | number
}

interface DropdownsErrorsDropdownnotfoundParams {
  id: string | number
}

interface DropdownsErrorsDropdownnameexistsParams {
  name: string | number
}

interface DropdownsErrorsOptionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnameexistsParams {
  name: string | number
}

interface DropdownsErrorsSelectionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnotindropdownParams {
  optionId: string | number; dropdownId: string | number
}

interface DropdownsErrorsMaxdepthexceededParams {
  maxDepth: string | number
}

interface DropdownsErrorsCategorymismatchParams {
  categoryId: string | number; dropdownCategoryId: string | number
}

interface DropdownsErrorsOptionnotfoundindropdownParams {
  optionId: string | number; dropdownName: string | number
}

interface DropdownsErrorsDropdownnotfoundincategoryParams {
  dropdownName: string | number; categoryName: string | number
}

interface EmployeesErrorsNotfoundParams {
  id: string | number
}

interface EmployeesSuccessDeletedParams {
  firstName: string | number; lastName: string | number
}

interface PersonsErrorsEmailexistsParams {
  email: string | number
}

interface PersonsErrorsNationalidexistsParams {
  nationalId: string | number
}

interface PersonsErrorsFathernameexistsParams {
  firstName: string | number; lastName: string | number
}

interface PersonsErrorsMothernameexistsParams {
  firstName: string | number; lastName: string | number
}

interface PersonsErrorsNamenoparentexistsParams {
  firstName: string | number; lastName: string | number
}

interface PersonsErrorsCannotdeleterelatedParams {
  firstName: string | number; lastName: string | number; relationsList: string | number
}

interface PersonsErrorsNotfoundParams {
  id: string | number
}

interface PersonsErrorsNamebirthdateexistsParams {
  firstName: string | number; lastName: string | number; birthDate: string | number
}

interface PersonsSuccessDeletedParams {
  firstName: string | number; lastName: string | number
}

interface SystemusersErrorsNotfoundParams {
  id: string | number
}

interface SystemusersSuccessDeletedParams {
  id: string | number
}

interface TrainingcoursesTrainingcoursesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesTrainingcoursesSuccessDeletedParams {
  name: string | number
}

interface TrainingcoursesCoursebatchesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesCoursebatchesSuccessDeletedParams {
  batchNumber: string | number; trainingCourseName: string | number
}

interface TrainingcoursesPersoncoursebatchesErrorsNotfoundParams {
  id: string | number
}

interface TrainingcoursesPersoncoursebatchesErrorsAlreadyenrolledParams {
  familyMemberId: string | number; courseBatchId: string | number
}

const TranslationKeys = {
  'dropdowns.errors.cannot_create_subcategory': 'dropdowns.errors.cannot_create_subcategory',
  'dropdowns.errors.category_has_children': 'dropdowns.errors.category_has_children',
  'dropdowns.errors.category_has_dropdowns': 'dropdowns.errors.category_has_dropdowns',
  'dropdowns.errors.category_mismatch': 'dropdowns.errors.category_mismatch',
  'dropdowns.errors.category_name_exists': 'dropdowns.errors.category_name_exists',
  'dropdowns.errors.category_not_found': 'dropdowns.errors.category_not_found',
  'dropdowns.errors.dropdown_has_options': 'dropdowns.errors.dropdown_has_options',
  'dropdowns.errors.dropdown_name_exists': 'dropdowns.errors.dropdown_name_exists',
  'dropdowns.errors.dropdown_not_found': 'dropdowns.errors.dropdown_not_found',
  'dropdowns.errors.dropdown_not_found_in_category': 'dropdowns.errors.dropdown_not_found_in_category',
  'dropdowns.errors.duplicate_options_not_allowed': 'dropdowns.errors.duplicate_options_not_allowed',
  'dropdowns.errors.invalid_selection_type': 'dropdowns.errors.invalid_selection_type',
  'dropdowns.errors.max_depth_exceeded': 'dropdowns.errors.max_depth_exceeded',
  'dropdowns.errors.multiple_selection_requires_at_least_one_option': 'dropdowns.errors.multiple_selection_requires_at_least_one_option',
  'dropdowns.errors.option_has_selections': 'dropdowns.errors.option_has_selections',
  'dropdowns.errors.option_name_exists': 'dropdowns.errors.option_name_exists',
  'dropdowns.errors.option_not_found': 'dropdowns.errors.option_not_found',
  'dropdowns.errors.option_not_found_in_dropdown': 'dropdowns.errors.option_not_found_in_dropdown',
  'dropdowns.errors.option_not_in_dropdown': 'dropdowns.errors.option_not_in_dropdown',
  'dropdowns.errors.selection_not_found': 'dropdowns.errors.selection_not_found',
  'dropdowns.errors.single_selection_exists': 'dropdowns.errors.single_selection_exists',
  'dropdowns.errors.single_selection_requires_one_option': 'dropdowns.errors.single_selection_requires_one_option',
  'employees.errors.already_employee': 'employees.errors.already_employee',
  'employees.errors.cannot_delete_with_system_account': 'employees.errors.cannot_delete_with_system_account',
  'employees.errors.not_found': 'employees.errors.not_found',
  'employees.success.deleted': 'employees.success.deleted',
  'persons.errors.cannot_delete_related': 'persons.errors.cannot_delete_related',
  'persons.errors.email_exists': 'persons.errors.email_exists',
  'persons.errors.father_name_exists': 'persons.errors.father_name_exists',
  'persons.errors.mother_name_exists': 'persons.errors.mother_name_exists',
  'persons.errors.name_birthdate_exists': 'persons.errors.name_birthdate_exists',
  'persons.errors.name_no_parent_exists': 'persons.errors.name_no_parent_exists',
  'persons.errors.national_id_exists': 'persons.errors.national_id_exists',
  'persons.errors.not_found': 'persons.errors.not_found',
  'persons.errors.person_details_exists': 'persons.errors.person_details_exists',
  'persons.errors.same_father_mother': 'persons.errors.same_father_mother',
  'persons.errors.self_father': 'persons.errors.self_father',
  'persons.errors.self_mother': 'persons.errors.self_mother',
  'persons.success.deleted': 'persons.success.deleted',
  'persons.validation.birth_date_max': 'persons.validation.birth_date_max',
  'persons.validation.birth_date_min': 'persons.validation.birth_date_min',
  'persons.validation.national_id_length': 'persons.validation.national_id_length',
  'system-users.errors.employee_has_system_account': 'system-users.errors.employee_has_system_account',
  'system-users.errors.not_found': 'system-users.errors.not_found',
  'system-users.errors.username_taken': 'system-users.errors.username_taken',
  'system-users.success.deleted': 'system-users.success.deleted',
  'training-courses.course-batches.errors.not_found': 'training-courses.course-batches.errors.not_found',
  'training-courses.course-batches.success.deleted': 'training-courses.course-batches.success.deleted',
  'training-courses.person-course-batches.errors.already_enrolled': 'training-courses.person-course-batches.errors.already_enrolled',
  'training-courses.person-course-batches.errors.not_found': 'training-courses.person-course-batches.errors.not_found',
  'training-courses.person-course-batches.success.deleted': 'training-courses.person-course-batches.success.deleted',
  'training-courses.training-courses.errors.not_found': 'training-courses.training-courses.errors.not_found',
  'training-courses.training-courses.success.deleted': 'training-courses.training-courses.success.deleted'
} as const;

export type TranslationKey = keyof typeof TranslationKeys;

// Type definitions for interpolation parameters
type NoParams = undefined;

// Placeholder type for type-safe interpolation
export interface TranslationInterpolations {
  'dropdowns.errors.cannot_create_subcategory': NoParams;
  'dropdowns.errors.category_has_children': NoParams;
  'dropdowns.errors.category_has_dropdowns': NoParams;
  'dropdowns.errors.category_mismatch': DropdownsErrorsCategorymismatchParams;
  'dropdowns.errors.category_name_exists': DropdownsErrorsCategorynameexistsParams;
  'dropdowns.errors.category_not_found': DropdownsErrorsCategorynotfoundParams;
  'dropdowns.errors.dropdown_has_options': NoParams;
  'dropdowns.errors.dropdown_name_exists': DropdownsErrorsDropdownnameexistsParams;
  'dropdowns.errors.dropdown_not_found': DropdownsErrorsDropdownnotfoundParams;
  'dropdowns.errors.dropdown_not_found_in_category': DropdownsErrorsDropdownnotfoundincategoryParams;
  'dropdowns.errors.duplicate_options_not_allowed': NoParams;
  'dropdowns.errors.invalid_selection_type': NoParams;
  'dropdowns.errors.max_depth_exceeded': DropdownsErrorsMaxdepthexceededParams;
  'dropdowns.errors.multiple_selection_requires_at_least_one_option': NoParams;
  'dropdowns.errors.option_has_selections': NoParams;
  'dropdowns.errors.option_name_exists': DropdownsErrorsOptionnameexistsParams;
  'dropdowns.errors.option_not_found': DropdownsErrorsOptionnotfoundParams;
  'dropdowns.errors.option_not_found_in_dropdown': DropdownsErrorsOptionnotfoundindropdownParams;
  'dropdowns.errors.option_not_in_dropdown': DropdownsErrorsOptionnotindropdownParams;
  'dropdowns.errors.selection_not_found': DropdownsErrorsSelectionnotfoundParams;
  'dropdowns.errors.single_selection_exists': NoParams;
  'dropdowns.errors.single_selection_requires_one_option': NoParams;
  'employees.errors.already_employee': NoParams;
  'employees.errors.cannot_delete_with_system_account': NoParams;
  'employees.errors.not_found': EmployeesErrorsNotfoundParams;
  'employees.success.deleted': EmployeesSuccessDeletedParams;
  'persons.errors.cannot_delete_related': PersonsErrorsCannotdeleterelatedParams;
  'persons.errors.email_exists': PersonsErrorsEmailexistsParams;
  'persons.errors.father_name_exists': PersonsErrorsFathernameexistsParams;
  'persons.errors.mother_name_exists': PersonsErrorsMothernameexistsParams;
  'persons.errors.name_birthdate_exists': PersonsErrorsNamebirthdateexistsParams;
  'persons.errors.name_no_parent_exists': PersonsErrorsNamenoparentexistsParams;
  'persons.errors.national_id_exists': PersonsErrorsNationalidexistsParams;
  'persons.errors.not_found': PersonsErrorsNotfoundParams;
  'persons.errors.person_details_exists': NoParams;
  'persons.errors.same_father_mother': NoParams;
  'persons.errors.self_father': NoParams;
  'persons.errors.self_mother': NoParams;
  'persons.success.deleted': PersonsSuccessDeletedParams;
  'persons.validation.birth_date_max': NoParams;
  'persons.validation.birth_date_min': NoParams;
  'persons.validation.national_id_length': NoParams;
  'system-users.errors.employee_has_system_account': NoParams;
  'system-users.errors.not_found': SystemusersErrorsNotfoundParams;
  'system-users.errors.username_taken': NoParams;
  'system-users.success.deleted': SystemusersSuccessDeletedParams;
  'training-courses.course-batches.errors.not_found': TrainingcoursesCoursebatchesErrorsNotfoundParams;
  'training-courses.course-batches.success.deleted': TrainingcoursesCoursebatchesSuccessDeletedParams;
  'training-courses.person-course-batches.errors.already_enrolled': TrainingcoursesPersoncoursebatchesErrorsAlreadyenrolledParams;
  'training-courses.person-course-batches.errors.not_found': TrainingcoursesPersoncoursebatchesErrorsNotfoundParams;
  'training-courses.person-course-batches.success.deleted': NoParams;
  'training-courses.training-courses.errors.not_found': TrainingcoursesTrainingcoursesErrorsNotfoundParams;
  'training-courses.training-courses.success.deleted': TrainingcoursesTrainingcoursesSuccessDeletedParams;
}
