// Generated by i18n-validator

interface DropdownsErrorsCategorynotfoundParams {
  id: string | number
}

interface DropdownsErrorsCategorynameexistsParams {
  name: string | number
}

interface DropdownsErrorsDropdownnotfoundParams {
  id: string | number
}

interface DropdownsErrorsDropdownnameexistsParams {
  name: string | number
}

interface DropdownsErrorsOptionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnameexistsParams {
  name: string | number
}

interface DropdownsErrorsSelectionnotfoundParams {
  id: string | number
}

interface DropdownsErrorsOptionnotindropdownParams {
  optionId: string | number; dropdownId: string | number
}

interface DropdownsErrorsMaxdepthexceededParams {
  maxDepth: string | number
}

const TranslationKeys = {
  'dropdowns.errors.category_has_children': 'dropdowns.errors.category_has_children',
  'dropdowns.errors.category_has_dropdowns': 'dropdowns.errors.category_has_dropdowns',
  'dropdowns.errors.category_name_exists': 'dropdowns.errors.category_name_exists',
  'dropdowns.errors.category_not_found': 'dropdowns.errors.category_not_found',
  'dropdowns.errors.dropdown_has_options': 'dropdowns.errors.dropdown_has_options',
  'dropdowns.errors.dropdown_name_exists': 'dropdowns.errors.dropdown_name_exists',
  'dropdowns.errors.dropdown_not_found': 'dropdowns.errors.dropdown_not_found',
  'dropdowns.errors.max_depth_exceeded': 'dropdowns.errors.max_depth_exceeded',
  'dropdowns.errors.option_has_selections': 'dropdowns.errors.option_has_selections',
  'dropdowns.errors.option_name_exists': 'dropdowns.errors.option_name_exists',
  'dropdowns.errors.option_not_found': 'dropdowns.errors.option_not_found',
  'dropdowns.errors.option_not_in_dropdown': 'dropdowns.errors.option_not_in_dropdown',
  'dropdowns.errors.selection_not_found': 'dropdowns.errors.selection_not_found',
  'dropdowns.errors.single_selection_exists': 'dropdowns.errors.single_selection_exists'
} as const;

export type TranslationKey = keyof typeof TranslationKeys;

// Type definitions for interpolation parameters
type NoParams = undefined;

// Placeholder type for type-safe interpolation
export interface TranslationInterpolations {
  'dropdowns.errors.category_has_children': NoParams;
  'dropdowns.errors.category_has_dropdowns': NoParams;
  'dropdowns.errors.category_name_exists': DropdownsErrorsCategorynameexistsParams;
  'dropdowns.errors.category_not_found': DropdownsErrorsCategorynotfoundParams;
  'dropdowns.errors.dropdown_has_options': NoParams;
  'dropdowns.errors.dropdown_name_exists': DropdownsErrorsDropdownnameexistsParams;
  'dropdowns.errors.dropdown_not_found': DropdownsErrorsDropdownnotfoundParams;
  'dropdowns.errors.max_depth_exceeded': DropdownsErrorsMaxdepthexceededParams;
  'dropdowns.errors.option_has_selections': NoParams;
  'dropdowns.errors.option_name_exists': DropdownsErrorsOptionnameexistsParams;
  'dropdowns.errors.option_not_found': DropdownsErrorsOptionnotfoundParams;
  'dropdowns.errors.option_not_in_dropdown': DropdownsErrorsOptionnotindropdownParams;
  'dropdowns.errors.selection_not_found': DropdownsErrorsSelectionnotfoundParams;
  'dropdowns.errors.single_selection_exists': NoParams;
}
